name: Run commands on different operating systems
on: ["push"]

jobs:
  test:
    name: test
    runs-on: windows-runner-vc2019
    steps:
      - uses: actions/checkout@v3
      - name: test conan build
        run: |
          choco install conan
          cd examples/libraries/poco/md5
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
          mkdir build
          cd build
          conan install ..
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          ./bin/md5
